### ISSUE TITLE
[Bug] Dropped files and folders does not work in V 6.0.1 (sort of works in v5.5.1)

### ISSUE THREAD

**Issue by chobo2** [react-dropzone/react-dropzone#679]
Hi

On your sample page the example does not work:  https://react-dropzone.netlify.com/#extending-dropzone

```
bundle.240f8038.js:39 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=StateHolder for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at invariant (bundle.240f8038.js:12)
    at A (bundle.240f8038.js:39)
    at bundle.240f8038.js:39
    at Jg (bundle.240f8038.js:39)
    at Lg (bundle.240f8038.js:39)
    at Sg (bundle.240f8038.js:39)
    at yh (bundle.240f8038.js:39)
    at zh (bundle.240f8038.js:39)
    at Wh (bundle.240f8038.js:39)
```

Also it makes no mention of how to get the 3rd party plugin.

In my local example using what I hope is the right plugin I get

```
index.js:249 Failed to generate preview for file {fileObject: File(180093), fullPath: "1.jpeg", lastModified: 1538421964806, lastModifiedDate: Mon Oct 01 2018 12:26:04 GMT-0700 (Pacific Daylight Time), name: "1.jpeg", …} TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at index.js:246
    at Array.forEach (<anonymous>)
    at index.js:243
```

```
        fileList.forEach(function (file) {
          if (!disablePreview) {
            try {
              file.preview = window.URL.createObjectURL(file); // eslint-disable-line no-param-reassign
            } catch (err) {
              if (process.env.NODE_ENV !== 'production') {
                console.error('Failed to generate preview for file', file, err); // eslint-disable-line no-console
              }
            }
          }
```

Edit I went to v5.5.1 and it sort of works I still see this error

```
index.js:235 Failed to generate preview for file {fileObject: File(137430), fullPath: "/New folder (2)/1.jpg", lastModified: 1538504216353, lastModifiedDate: Tue Oct 02 2018 11:16:56 GMT-0700 (Pacific Daylight Time), name: "1.jpg", …} TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at index.js:232
    at Array.forEach (<anonymous>)
    at index.js:229
```

but it also extracts the data out though when I drag a folder in and then look at each file in the "files" array "webkitRelativePath" is empty would have thought this would be populated.

**Comment by rolandjitsu** [comment]
@chobo2 see https://github.com/react-dropzone/react-dropzone/pull/682. It has been fixed by providing a different plugin library.
